#!/usr/bin/env bash
#
# End-to-end verification of the quiz and progress systems — `npm run verify`
# from the backend directory, against a running server with `npm run seed` data.
#
# Every line asserts an expected HTTP status or row count. A FAIL is a real
# defect. Written as a shell script rather than with a test runner because the
# backend has no test dependency installed and these assertions are about HTTP
# responses, not units.
#
# Repeatable: it normalizes the progress state before asserting on it, so it does
# not depend on what a previous run left behind.

set -u

API=${API:-http://localhost:1337}
PASSWORD=Demo1234!
COURSE_SLUG=intro-to-typescript
# The post that has to be unpublished for the visibility assertions to mean
# anything. Looked up by slug for the same reason the course is: documentIds are
# regenerated by every fresh seed.
DRAFT_BLOG_SLUG=unpublished-draft-post

pass=0
fail=0

# --------------------------------------------------------------------------- #
# Helpers                                                                     #
# --------------------------------------------------------------------------- #

# All curl calls pass -g. Without it curl treats the `[` in `filters[x]` as URL
# globbing and never sends the request, which reads as "zero rows" — a silent
# false pass.
CURL="curl -s -g"

check() {
  if [ "$2" = "$3" ]; then
    printf '  PASS  %-56s %s\n' "$1" "$3"
    pass=$((pass + 1))
  else
    printf '  FAIL  %-56s got=%s want=%s\n' "$1" "$3" "$2"
    fail=$((fail + 1))
  fi
}

# status <method> <path> [token] [json-body]
status() {
  local m=$1 p=$2 t=${3:-} b=${4:-}
  if [ -n "$b" ]; then
    $CURL -o /dev/null -w '%{http_code}' -X "$m" "$API$p" \
      ${t:+-H "Authorization: Bearer $t"} -H 'Content-Type: application/json' -d "$b"
  else
    $CURL -o /dev/null -w '%{http_code}' -X "$m" "$API$p" ${t:+-H "Authorization: Bearer $t"}
  fi
}

get() { $CURL "$API$1" ${2:+-H "Authorization: Bearer $2"}; }

post() {
  $CURL -X POST "$API$1" ${2:+-H "Authorization: Bearer $2"} \
    -H 'Content-Type: application/json' -d "$3"
}

# The PUT twin of `post`, for the handlers whose *body* is asserted rather than
# their status — role assignment and the final-quiz link both report what they
# actually stored, and reading that back is the only way to tell a write that
# landed from one that was accepted and dropped.
put() {
  $CURL -X PUT "$API$1" ${2:+-H "Authorization: Bearer $2"} \
    -H 'Content-Type: application/json' -d "$3"
}

# Counts distinct documentIds in a response. `grep -c` counts matching *lines*
# and the body is a single line, so it would report 1 for any non-empty response.
rows() { get "$1" "${2:-}" | grep -oP '"documentId":"\K[^"]+' | sort -u | wc -l; }

# documentIds in response order.
ids() { get "$1" "${2:-}" | grep -oP '"documentId":"\K[^"]+'; }

# num <json-key> — reads a number out of the last response piped in.
num() { grep -oP "\"$1\":\"?\K[0-9.]+"; }

# --------------------------------------------------------------------------- #
# Tokens                                                                      #
# --------------------------------------------------------------------------- #
#
# `/api/auth/local` is rate-limited by users-permissions (5 attempts per
# identifier per 5 minutes). Re-running this script exhausted it, and a login
# that returns no token makes an authorized request look like a denied one — an
# anonymous PUT is 403, exactly like a forbidden one. So tokens are cached
# between runs; they are valid for 30 days.
#
# Keyed by API host, because a JWT is only meaningful to the instance that signed
# it: production and local use different JWT_SECRETs, so one shared cache file
# means every switch between environments discards six still-valid tokens and
# logs in again.
CACHE=${TOKEN_CACHE:-/tmp/lms-verify-tokens.$(printf '%s' "$API" |
  sed -e 's#^https\?://##' -e 's#[^A-Za-z0-9._-]#-#g').env}
touch "$CACHE"

# The email a token authenticates as — identity, not mere validity. A cached
# token that authenticates as the *wrong* user is far worse than no token: a
# cache in which T_I2 held the admin's JWT turned "another instructor cannot
# delete this course" into an admin deleting it, and the seed course was gone,
# with its lessons and quizzes left orphaned. Checking only for HTTP 200 does
# not catch that; checking who answered does.
token_email() {
  [ -n "${1:-}" ] || return 0
  $CURL -H "Authorization: Bearer $1" "$API/api/users/me" | grep -oP '"email":"\K[^"]+'
}

# The numeric id behind a token. Needed because two assertions below have to name
# a user in a query string or a payload, and numeric ids are no more portable
# between environments than documentIds are — see the note where this is called.
token_user_id() {
  [ -n "${1:-}" ] || return 0
  $CURL -H "Authorization: Bearer $1" "$API/api/users/me" | grep -oP '"id":\K[0-9]+' | head -1
}

ensure_token() {
  local var=$1 email=$2 cached token code attempt body who
  cached=$(grep -oP "^$var=\K.*" "$CACHE" | tail -1 || true)

  if [ "$(token_email "${cached:-}")" = "$email" ]; then
    export "$var=$cached"
    return 0
  fi

  for attempt in 1 2 3; do
    # A per-account response file, removed first. Sharing one path meant that if a
    # login did not overwrite it the next read picked up the *previous* account's
    # response — which is how a cache ended up holding the admin's JWT under all
    # six names.
    body=/tmp/lms-verify-login.$var.json
    rm -f "$body"

    code=$($CURL -o "$body" -w '%{http_code}' -X POST "$API/api/auth/local" \
      -H 'Content-Type: application/json' \
      -d "{\"identifier\":\"$email\",\"password\":\"$PASSWORD\"}")
    token=$(grep -oP '"jwt":"\K[^"]+' "$body" 2>/dev/null || true)
    who=$(grep -oP '"email":"\K[^"]+' "$body" 2>/dev/null | head -1 || true)

    # The token is cached only if the same response also identifies the account it
    # was asked for, so a token can never be filed under the wrong name.
    if [ -n "$token" ] && [ "$who" = "$email" ]; then
      grep -v "^$var=" "$CACHE" > "$CACHE.tmp" 2>/dev/null || true
      mv "$CACHE.tmp" "$CACHE"
      printf '%s=%s\n' "$var" "$token" >> "$CACHE"
      export "$var=$token"
      return 0
    fi

    echo "  login $email -> HTTP $code (as '${who:-nobody}'); waiting out the rate limit ($attempt/3)" >&2
    sleep 65
  done

  echo "LOGIN FAILED: $email (HTTP $code)" >&2
  return 1
}

# A second student and a second instructor exist only to prove that role alone
# does not grant access to another person's data or another instructor's course.
register_if_missing() {
  $CURL -o /dev/null -X POST "$API/api/auth/local/register" -H 'Content-Type: application/json' \
    -d "{\"username\":\"$1\",\"email\":\"$2\",\"password\":\"$PASSWORD\"}"
}

register_if_missing student2 student2@demo.test
register_if_missing instructor2 instructor2@demo.test

ensure_token T_S1 student@demo.test || exit 1
ensure_token T_S2 student2@demo.test || exit 1
ensure_token T_I1 instructor@demo.test || exit 1
ensure_token T_I2 instructor2@demo.test || exit 1
ensure_token T_CM cm@demo.test || exit 1
ensure_token T_ADMIN admin@demo.test || exit 1

# Then prove, before a single assertion runs, that every token authenticates as
# the person it is named for. Two failure modes this closes:
#
#   * A token that authenticates as nobody makes the whole suite fall through to
#     anonymous requests, and anonymous results look like passes — a request with
#     no token is 403 on a protected route, exactly like a denied one.
#   * A token that authenticates as the *wrong* person turns the negative checks
#     into privileged operations. The DELETE and PUT assertions below expect 403;
#     run with an over-privileged token they succeed, and this suite stops
#     verifying the system and starts damaging it.
for account in "T_S1:student@demo.test" "T_S2:student2@demo.test" \
               "T_I1:instructor@demo.test" "T_I2:instructor2@demo.test" \
               "T_CM:cm@demo.test" "T_ADMIN:admin@demo.test"; do
  name=${account%%:*}
  want=${account#*:}
  got=$(token_email "${!name}")
  if [ "$got" != "$want" ]; then
    echo "$name authenticates as '${got:-nobody}', not $want." >&2
    echo "Delete $CACHE and re-run to fetch fresh tokens." >&2
    exit 1
  fi
done

# student1's numeric id, resolved rather than assumed. Two assertions below need
# to name "a user who is not the caller", and the obvious shortcut — hardcoding 1,
# since a fresh seed makes student@demo.test the first user — is wrong the moment
# the suite runs anywhere else. Against production, student2 held id 1 and
# student1 held 3, so "another student's progress is not readable" was asking
# student2 to read *their own* progress; the API correctly answered 200 and the
# suite reported a security failure that did not exist.
S1_USER_ID=$(token_user_id "$T_S1")
if [ -z "${S1_USER_ID:-}" ]; then
  echo "Could not read student@demo.test's numeric id from /api/users/me." >&2
  exit 1
fi

# instructor2 registers into the default role; it needs the instructor role for the
# instructor-vs-instructor ownership checks to mean anything. Until role assignment
# moved into the app this was a manual step in Settings -> Users & Permissions ->
# Users, and a run that skipped it passed *vacuously*: every "another instructor
# cannot ..." assertion below expects 403, and a student is 403 too. So the suite
# now assigns the role itself, through the same endpoint the admin dashboard uses,
# and refuses to continue without it.
#
# The numeric ids come from /api/users/me for the same reason S1_USER_ID does — see
# the note above it. The admin's own id is needed for the one assertion that has to
# name the caller: an admin may not change their own role.
I2_USER_ID=$(token_user_id "$T_I2")
ADMIN_USER_ID=$(token_user_id "$T_ADMIN")
if [ -z "${I2_USER_ID:-}" ] || [ -z "${ADMIN_USER_ID:-}" ]; then
  echo "Could not read the numeric ids of instructor2@demo.test / admin@demo.test." >&2
  exit 1
fi

# Read through /api/admin/users rather than /api/users?populate=role: the latter
# needs `find` on the user type *and* on the role type, and the second grant also
# opens /api/users-permissions/roles — every role with its full permission set.
#
# The email is confirmed present before the role is read, because on an empty match
# the first `"type"` in the payload belongs to the assignable-roles list that ships
# alongside the users, and that would report someone else's role as instructor2's.
role_of() {
  local body
  body=$(get "/api/admin/users?q=$1" "$T_ADMIN")
  printf '%s' "$body" | grep -q "\"email\":\"$1\"" || return 0
  printf '%s' "$body" | grep -oP '"type":"\K[^"]+' | head -1
}

I2_ROLE=$(role_of instructor2@demo.test || true)
if [ "${I2_ROLE:-}" != "instructor" ]; then
  echo "  instructor2@demo.test is in '${I2_ROLE:-no role}' — assigning the instructor role."
  status PUT "/api/admin/users/$I2_USER_ID/role" "$T_ADMIN" '{"role":"instructor"}' > /dev/null
  I2_ROLE=$(role_of instructor2@demo.test || true)
fi
if [ "${I2_ROLE:-}" != "instructor" ]; then
  echo "instructor2@demo.test is still not an instructor (found '${I2_ROLE:-no role}')." >&2
  echo "Run 'npm run permissions' in backend/ so the admin role holds" >&2
  echo "api::admin.admin.users and api::admin.admin.setUserRole, then re-run." >&2
  exit 1
fi

# --------------------------------------------------------------------------- #
# Resolve documentIds                                                         #
# --------------------------------------------------------------------------- #
#
# documentIds are random cuid2s regenerated by every fresh seed, so they are
# looked up by natural key rather than hardcoded.
COURSE=$(ids "/api/courses?filters[slug]=$COURSE_SLUG&fields[0]=slug" "$T_ADMIN" | head -1)
[ -n "$COURSE" ] || { echo "Course '$COURSE_SLUG' not found — run 'npm run seed' first."; exit 1; }

readarray -t LESSONS < <(ids \
  "/api/lessons?filters[course][documentId]=$COURSE&fields[0]=title&sort=sequenceOrder:asc&pagination[pageSize]=100" \
  "$T_ADMIN")
# A quiz has no title of its own — which of the two course relations is set is
# what makes it the final quiz or a practice one — so no `fields` here.
FINAL_QUIZ=$(ids "/api/quizzes?filters[course][documentId]=$COURSE" "$T_ADMIN" | head -1)
PRACTICE_QUIZ=$(ids "/api/quizzes?filters[parent_course][documentId]=$COURSE" "$T_ADMIN" | head -1)

# Normalized for the same reason progress is: publishing is one-way, so any
# environment that has ever had this post published stays broken. A production
# database restored from a snapshot taken while it was published fails every
# assertion below, and the post is publicly visible in the meantime.
normalize_draft_blog() {
  local id
  id=$(ids "/api/blogs?filters[slug]=$DRAFT_BLOG_SLUG&fields[0]=slug" "$T_ADMIN" | head -1)
  [ -n "$id" ] || return 0
  status PUT "/api/blogs/$id" "$T_ADMIN" '{"data":{"currentStatus":"draft"}}' > /dev/null
}

normalize_draft_blog

# student2 is the account every "owns nothing" assertion leans on: enrolled nowhere,
# no progress, no results. That is a *precondition*, and nothing established it. This
# suite cleans up after itself, but requesting enrolment as student2 once in the
# browser leaves a row that then survives every run afterwards — and one stray
# approved enrollment turns five assertions into failures that look like leaks and are
# not: an enrolled student may legitimately read the questions of a quiz in their own
# course, so the redaction checks correctly report content reaching them.
#
# Removed loudly rather than silently. Deleting somebody's rows is not something a
# verification script should do without saying so.
normalize_student2() {
  local kind stray
  for kind in enrollments lesson-progresses quiz-results; do
    for stray in $(ids "/api/$kind?pagination[pageSize]=100" "$T_S2"); do
      echo "  removing a stray $kind row left on student2@demo.test ($stray)"
      status DELETE "/api/$kind/$stray" "$T_ADMIN" > /dev/null
    done
  done
}

normalize_student2

PUBLISHED_BLOG=$(ids '/api/blogs?filters[currentStatus]=published&fields[0]=title' "$T_ADMIN" | head -1)
DRAFT_BLOG=$(ids '/api/blogs?filters[currentStatus]=draft&fields[0]=title' "$T_ADMIN" | head -1)

TOTAL_LESSONS=${#LESSONS[@]}
if [ "$TOTAL_LESSONS" -lt 5 ] || [ -z "$FINAL_QUIZ" ] || [ -z "$PRACTICE_QUIZ" ] ||
   [ -z "$PUBLISHED_BLOG" ] || [ -z "$DRAFT_BLOG" ]; then
  # Every value, not a selection of them: the original message printed lessons
  # and the two quizzes only, so a missing blog post — the one thing a restored
  # production database is actually likely to get wrong — showed up as a bail-out
  # with three healthy-looking numbers next to it.
  echo "Seed data incomplete. Run 'npm run seed'."
  echo "  lessons         $TOTAL_LESSONS (want 5 or more)"
  echo "  final quiz      ${FINAL_QUIZ:-MISSING}"
  echo "  practice quiz   ${PRACTICE_QUIZ:-MISSING}"
  echo "  published blog  ${PUBLISHED_BLOG:-MISSING}"
  echo "  draft blog      ${DRAFT_BLOG:-MISSING (is '$DRAFT_BLOG_SLUG' published?)}"
  exit 1
fi

# Three of five complete is the state every assertion below is written against.
normalize_progress() {
  local i
  for i in 0 1 2; do
    post "/api/lessons/${LESSONS[$i]}/complete" "$T_S1" '{}' > /dev/null
  done
  for i in 3 4; do
    post '/api/lesson-progresses' "$T_S1" \
      "{\"data\":{\"lesson\":\"${LESSONS[$i]}\",\"completed\":false}}" > /dev/null
  done
}

normalize_progress

ENROLLMENT=$(ids '/api/enrollments' "$T_S1" | head -1)
S1_PROGRESS=$(ids '/api/lesson-progresses?pagination[pageSize]=100' "$T_S1" | head -1)

# --------------------------------------------------------------------------- #
echo
echo "=== the answer key must never reach the wire ==="
# correctOptionIndex is `private`, so it is stripped from every REST response
# while remaining readable by the Document Service, which is what makes
# server-side grading possible.
for probe in "direct populate:/api/quizzes/$FINAL_QUIZ?populate=Question" \
             "populate=*:/api/quizzes/$FINAL_QUIZ?populate=*" \
             "nested via course:/api/courses/$COURSE?populate[final_quiz][populate]=Question"; do
  label=${probe%%:*}
  url=${probe#*:}
  for who in "student:$T_S1" "admin:$T_ADMIN"; do
    check "$label (${who%%:*})" 0 "$(get "$url" "${who#*:}" | grep -o correctOptionIndex | wc -l)"
  done
done
# The questions must still be readable, or the quiz cannot be taken at all.
check "questions still returned to the student" 4 \
  "$(get "/api/quizzes/$FINAL_QUIZ?populate=Question" "$T_S1" | grep -o '"questionText"' | wc -l)"
check "options still returned to the student" 4 \
  "$(get "/api/quizzes/$FINAL_QUIZ?populate=Question" "$T_S1" | grep -o '"options"' | wc -l)"

# --------------------------------------------------------------------------- #
echo
echo "=== except to whoever may rewrite it ==="
# The one exception to the section above, and the reason the in-app quiz editor can
# exist at all: an author opening a saved quiz has to see which option is marked, or
# every field would render blank and the first save would wipe the key.
#
# So `GET /quizzes/:id/manage` returns it — behind `can-manage-quiz`, the same policy
# that guards the writes, and assembling its payload field by field rather than
# spreading the document, because this is the one place the key leaves the server.
MANAGED=$(get "/api/quizzes/$FINAL_QUIZ/manage" "$T_ADMIN")
check "an admin reads the key back" 4 \
  "$(printf '%s' "$MANAGED" | grep -o correctOptionIndex | wc -l)"
# Not merely that a key came back, but that it is the *same* key the grader uses:
# these are the four answers that score 100 further down.
check "and it is the key grading scores against" 0121 \
  "$(printf '%s' "$MANAGED" | grep -oP '"correctOptionIndex":\K[0-9]+' | tr -d '\n')"
# A quiz has no type column, so the editor titles itself from the relation that is
# set. Getting this wrong would offer a final quiz under a lesson's heading.
check "and it says which kind of quiz this is" '"isFinal":true' \
  "$(printf '%s' "$MANAGED" | grep -o '"isFinal":true')"
check "the course's own instructor reads it too" 4 \
  "$(get "/api/quizzes/$FINAL_QUIZ/manage" "$T_I1" | grep -o correctOptionIndex | wc -l)"
check "and a content manager, who may author anywhere" 4 \
  "$(get "/api/quizzes/$FINAL_QUIZ/manage" "$T_CM" | grep -o correctOptionIndex | wc -l)"
check "an instructor who does not own the course cannot" 403 \
  "$(status GET "/api/quizzes/$FINAL_QUIZ/manage" "$T_I2")"
# The student holds quiz.find and quiz.findOne, so this has to be refused by the
# separate `manage` action rather than by quiz permissions in general.
check "an enrolled student cannot" 403 \
  "$(status GET "/api/quizzes/$FINAL_QUIZ/manage" "$T_S1")"
check "nor an anonymous caller" 403 "$(status GET "/api/quizzes/$FINAL_QUIZ/manage")"

# --------------------------------------------------------------------------- #
echo
echo "=== the inside of a course is what enrolment buys ==="
# A course's *shape* — its lessons' titles, which of them carry a quiz, that a
# final and a practice quiz exist — is the catalog and stays readable. Its
# contents are not: lesson bodies, and above all quiz questions, which are only
# ever meant to be seen while actually taking the quiz.
#
# T_S2 is enrolled in nothing, which is the case that was leaking: `public` holds
# neither lesson.find nor quiz.find, so an anonymous caller never had the relations
# at all, but any signed-in account did.
check "an unenrolled student gets no questions" 0 \
  "$(get "/api/quizzes/$FINAL_QUIZ?populate=Question" "$T_S2" | grep -o '"questionText"' | wc -l)"
check "nor the options they choose between" 0 \
  "$(get "/api/quizzes/$FINAL_QUIZ?populate=Question" "$T_S2" | grep -o '"options"' | wc -l)"
check "nor every quiz on the platform at once" 0 \
  "$(get '/api/quizzes?populate[Question]=true&pagination[pageSize]=100' "$T_S2" | grep -o '"questionText"' | wc -l)"
check "nor a lesson body" 0 \
  "$(get "/api/lessons/${LESSONS[0]}" "$T_S2" | grep -o '"content"' | wc -l)"
check "nor one reached through the course" 0 \
  "$(get "/api/courses/$COURSE?populate[lessons]=true" "$T_S2" | grep -o '"content"' | wc -l)"

# REST populate nests to arbitrary depth, which is why the gate is applied to the
# response and not to the incoming query: a query-shaped guard would have to
# anticipate every one of these separately, and they are not a closed set.
check "nor through a deep populate to the final quiz" 0 \
  "$(get "/api/courses/$COURSE?populate[final_quiz][populate][0]=Question" "$T_S2" | grep -o '"questionText"' | wc -l)"
check "nor through the practice quiz" 0 \
  "$(get "/api/courses/$COURSE?populate[practice_quizzes][populate][0]=Question" "$T_S2" | grep -o '"questionText"' | wc -l)"
check "nor by looping back from a quiz to its course's lessons" 0 \
  "$(get "/api/quizzes/$FINAL_QUIZ?populate[course][populate][0]=lessons" "$T_S2" | grep -o '"content"' | wc -l)"
# The lesson-quiz chain (`course→lessons→quiz→Question`) is asserted in the smoke
# section instead: the seeded course has no lesson quizzes, so the same check here
# would pass with the gate removed entirely.

# The shape genuinely must survive: it is what a student reads to decide whether
# the course is worth requesting.
check "but every lesson still arrives, titled and ordered" "$TOTAL_LESSONS" \
  "$(get "/api/courses/$COURSE?populate[lessons]=true" "$T_S2" | grep -o '"sequenceOrder"' | wc -l)"
check "and the quiz is still listed as existing" 1 \
  "$(rows "/api/quizzes?filters[documentId]=$FINAL_QUIZ" "$T_S2")"

# Over-redaction is the other half of the bug, and the more expensive one: an
# instructor who cannot read their own material cannot check it before publishing,
# and the authoring screens stop working.
check "the course's instructor still reads the questions" 4 \
  "$(get "/api/quizzes/$FINAL_QUIZ?populate=Question" "$T_I1" | grep -o '"questionText"' | wc -l)"
check "and an admin does too" 4 \
  "$(get "/api/quizzes/$FINAL_QUIZ?populate=Question" "$T_ADMIN" | grep -o '"questionText"' | wc -l)"
check "the instructor still reads the lesson body" 1 \
  "$(get "/api/lessons/${LESSONS[0]}" "$T_I1" | grep -o '"content"' | wc -l)"
check "and every body in the course at once" "$TOTAL_LESSONS" \
  "$(get "/api/courses/$COURSE?populate[lessons]=true" "$T_ADMIN" | grep -o '"content"' | wc -l)"
# The twin of the deep-populate checks above: without this they would still pass if
# the chain simply did not resolve, and a guard that is never reached is not a guard.
check "and the deep populate does resolve for them" 4 \
  "$(get "/api/courses/$COURSE?populate[final_quiz][populate][0]=Question" "$T_ADMIN" \
    | grep -o '"questionText"' | wc -l)"
# The enrolled student, who is the whole point: same request, same course, allowed.
check "the enrolled student reads the bodies too" "$TOTAL_LESSONS" \
  "$(get "/api/courses/$COURSE?populate[lessons]=true" "$T_S1" | grep -o '"content"' | wc -l)"

echo
echo "=== progress tracking ==="
P=$(get "/api/courses/$COURSE/progress" "$T_S1")
check "completedLessons" 3 "$(printf '%s' "$P" | num completedLessons)"
check "totalLessons" "$TOTAL_LESSONS" "$(printf '%s' "$P" | num totalLessons)"
check "progressPercent" 60 "$(printf '%s' "$P" | num progressPercent)"

R=$(post "/api/lessons/${LESSONS[0]}/complete" "$T_S1" '{}')
check "re-completing a finished lesson stays 3" 3 "$(printf '%s' "$R" | num completedLessons)"
check "and the percentage does not drift" 60 "$(printf '%s' "$R" | num progressPercent)"

R=$(post "/api/lessons/${LESSONS[3]}/complete" "$T_S1" '{}')
check "completing the 4th lesson -> 4" 4 "$(printf '%s' "$R" | num completedLessons)"
check "completing the 4th lesson -> 80%" 80 "$(printf '%s' "$R" | num progressPercent)"

R=$(post "/api/lessons/${LESSONS[4]}/complete" "$T_S1" '{}')
check "completing the 5th lesson -> 5" 5 "$(printf '%s' "$R" | num completedLessons)"
check "completing the 5th lesson -> 100%" 100 "$(printf '%s' "$R" | num progressPercent)"

check "one progress document per lesson, not per click" 5 \
  "$(rows '/api/lesson-progresses?pagination[pageSize]=100' "$T_S1")"

normalize_progress
check "un-completing returns to 3" 3 \
  "$(get "/api/courses/$COURSE/progress" "$T_S1" | num completedLessons)"

echo
echo "=== server-side grading ==="
R=$(post "/api/quizzes/$FINAL_QUIZ/submit" "$T_S1" '{"answers":[0,1,2,1]}')
check "all correct -> 100" 100 "$(printf '%s' "$R" | num score)"
check "all correct -> 4 of 4" 4 "$(printf '%s' "$R" | num correctCount)"
check "the final quiz is recorded" true "$(printf '%s' "$R" | grep -oP '"recorded":\K(true|false)')"
check "per-question feedback returned" 4 "$(printf '%s' "$R" | grep -o '"correct"' | wc -l)"
check "the graded response leaks no answer key" 0 \
  "$(printf '%s' "$R" | grep -o correctOptionIndex | wc -l)"

R=$(post "/api/quizzes/$FINAL_QUIZ/submit" "$T_S1" '{"answers":[0,1,9,9]}')
check "two of four -> 50" 50 "$(printf '%s' "$R" | num score)"

R=$(post "/api/quizzes/$PRACTICE_QUIZ/submit" "$T_S1" '{"answers":[0,1,0]}')
check "a practice quiz is still scored" 100 "$(printf '%s' "$R" | num score)"
check "but a practice quiz is not recorded" false \
  "$(printf '%s' "$R" | grep -oP '"recorded":\K(true|false)')"

check "one stored result, for the final quiz only" 1 \
  "$(rows '/api/quiz-results?pagination[pageSize]=100' "$T_S1")"
check "the stored score is the latest submission" 50 \
  "$(get '/api/quiz-results?pagination[pageSize]=100' "$T_S1" | num latestScore)"

check "a non-enrolled student cannot submit" 403 \
  "$(status POST "/api/quizzes/$FINAL_QUIZ/submit" "$T_S2" '{"answers":[0,1,2,1]}')"
check "an instructor cannot submit" 403 \
  "$(status POST "/api/quizzes/$FINAL_QUIZ/submit" "$T_I1" '{"answers":[0,1,2,1]}')"
check "a malformed submission is rejected" 400 \
  "$(status POST "/api/quizzes/$FINAL_QUIZ/submit" "$T_S1" '{"answers":"nonsense"}')"

echo
echo "=== each role sees only its own rows ==="
# The scope is resolved server-side and injected as a documentId allowlist; see
# scopeQueryToDocuments. student2 and instructor2 own nothing here.
#
# One progress document exists per lesson — normalize_progress touches all five,
# completing three of them — so the owner's document count is the lesson count,
# not the completed count.
#
# Two guarantees here, so two kinds of assertion. A student's scope is *exactly*
# their own rows, which is an equality. A manager's scope is a superset — the
# course's instructor sees their students' rows, a content_manager and an admin
# see everyone's — so counting rows there only holds while the seeded student is
# the only person in the database. Against production they were not: one real
# signup enrolling in the seeded course turned "enrollments — owning instructor"
# into got=2 want=1, a failure that says nothing about scoping. Containment is
# the property that actually matters, and it survives other people using the app.

# How many of $owned the token can see. Equal to the total when the manager's
# scope covers the owner, lower when rows are being hidden from someone who
# should see them.
seen_all_of() {
  local path=$1 token=$2 owned=$3 seen id n=0
  seen=$(ids "/api/$path?pagination[pageSize]=100" "$token")
  for id in $owned; do
    if printf '%s\n' "$seen" | grep -qxF "$id"; then n=$((n + 1)); fi
  done
  echo "$n"
}

for ep in "lesson-progresses:$TOTAL_LESSONS" quiz-results:1 enrollments:1; do
  path=${ep%%:*}
  own=${ep#*:}
  owned=$(ids "/api/$path?pagination[pageSize]=100" "$T_S1")

  check "$path — owning student" "$own" "$(printf '%s\n' "$owned" | grep -c . || true)"
  check "$path — other student" 0 "$(rows "/api/$path?pagination[pageSize]=100" "$T_S2")"
  check "$path — owning instructor" "$own" "$(seen_all_of "$path" "$T_I1" "$owned")"
  check "$path — other instructor" 0 "$(rows "/api/$path?pagination[pageSize]=100" "$T_I2")"
  check "$path — content_manager" "$own" "$(seen_all_of "$path" "$T_CM" "$owned")"
  check "$path — admin" "$own" "$(seen_all_of "$path" "$T_ADMIN" "$owned")"
done

# The scope is intersected with the client's filters rather than merged into
# them, so no filter a client can write widens it.
check "a hostile client filter cannot widen the scope" 0 \
  "$(rows '/api/lesson-progresses?filters[completed]=true&pagination[pageSize]=100' "$T_S2")"
check "pagination meta reflects the scope, not the table" 0 \
  "$(get '/api/lesson-progresses?pagination[pageSize]=1' "$T_S2" | num total)"

echo
echo "=== findOne ownership ==="
check "another student cannot read a progress row" 403 \
  "$(status GET "/api/lesson-progresses/$S1_PROGRESS" "$T_S2")"
check "the owner can" 200 "$(status GET "/api/lesson-progresses/$S1_PROGRESS" "$T_S1")"
check "another instructor cannot" 403 "$(status GET "/api/lesson-progresses/$S1_PROGRESS" "$T_I2")"
check "the course's instructor can" 200 "$(status GET "/api/lesson-progresses/$S1_PROGRESS" "$T_I1")"
check "another student cannot read an enrollment" 403 \
  "$(status GET "/api/enrollments/$ENROLLMENT" "$T_S2")"
check "the owner can" 200 "$(status GET "/api/enrollments/$ENROLLMENT" "$T_S1")"

echo
echo "=== progress cannot be forged ==="
check "another student's progress is not readable" 403 \
  "$(status GET "/api/courses/$COURSE/progress?userId=$S1_USER_ID" "$T_S2")"
check "a non-enrolled student cannot record progress" 403 \
  "$(status POST '/api/lesson-progresses' "$T_S2" \
    "{\"data\":{\"lesson\":\"${LESSONS[0]}\",\"user\":$S1_USER_ID,\"completed\":true}}")"
check "and the owner's row count is unchanged" "$TOTAL_LESSONS" \
  "$(rows '/api/lesson-progresses?pagination[pageSize]=100' "$T_S1")"
check "a non-enrolled student cannot complete a lesson" 403 \
  "$(status POST "/api/lessons/${LESSONS[0]}/complete" "$T_S2" '{}')"
check "enrolling twice is a conflict, not a second row" 409 \
  "$(status POST '/api/enrollments' "$T_S1" "{\"data\":{\"course\":\"$COURSE\"}}")"

echo
echo "=== course, lesson and quiz ownership ==="
# The successful writes re-send the seeded title, so a passing run leaves the
# demo content exactly as it found it. A course has no `level` attribute — an
# invalid key is a 400, which would fail these two for the wrong reason.
check "the owning instructor can update the course" 200 \
  "$(status PUT "/api/courses/$COURSE" "$T_I1" '{"data":{"title":"Intro to TypeScript"}}')"
check "another instructor cannot" 403 \
  "$(status PUT "/api/courses/$COURSE" "$T_I2" '{"data":{"title":"Hijacked"}}')"
check "another instructor cannot delete it" 403 "$(status DELETE "/api/courses/$COURSE" "$T_I2")"
check "a student cannot update it" 403 \
  "$(status PUT "/api/courses/$COURSE" "$T_S1" '{"data":{"title":"Hijacked"}}')"
check "an admin can update any course" 200 \
  "$(status PUT "/api/courses/$COURSE" "$T_ADMIN" '{"data":{"title":"Intro to TypeScript"}}')"
# Adding a lesson to someone else's course inflates its total and so distorts
# every enrolled student's percentage.
check "another instructor cannot add a lesson" 403 \
  "$(status POST '/api/lessons' "$T_I2" \
    "{\"data\":{\"title\":\"Injected\",\"course\":\"$COURSE\",\"sequenceOrder\":99}}")"
check "another instructor cannot edit a lesson" 403 \
  "$(status PUT "/api/lessons/${LESSONS[0]}" "$T_I2" '{"data":{"title":"Hijacked"}}')"
# Payloads use `Question` rather than a title because a quiz has no title field;
# an invalid key would make these fail with 400 and pass for the wrong reason.
check "another instructor cannot edit a quiz" 403 \
  "$(status PUT "/api/quizzes/$FINAL_QUIZ" "$T_I2" '{"data":{"Question":[]}}')"
check "another instructor cannot attach a quiz to the course" 403 \
  "$(status POST '/api/quizzes' "$T_I2" "{\"data\":{\"parent_course\":\"$COURSE\"}}")"
# If one of those deletes had actually gone through, every assertion after this
# point would fail for the wrong reason and the demo data would be gone. Fail
# loudly here instead. It has happened: a token cache in which T_I2 held the
# admin's JWT turned the DELETE above into a successful one.
check "the course survived the ownership checks" 1 \
  "$(rows "/api/courses?filters[documentId]=$COURSE" "$T_ADMIN")"

echo
echo "=== unpublished blog posts stay invisible ==="
check "anonymous sees only published" 1 "$(rows '/api/blogs?pagination[pageSize]=100')"
check "a student sees only published" 1 "$(rows '/api/blogs?pagination[pageSize]=100' "$T_S1")"
check "the author sees their own draft" 2 "$(rows '/api/blogs?pagination[pageSize]=100' "$T_CM")"
check "an admin sees every post" 2 "$(rows '/api/blogs?pagination[pageSize]=100' "$T_ADMIN")"
# Asking for drafts returns an empty page rather than the drafts: the visibility
# scope is intersected with the client's filter.
check "anonymous asking for drafts gets nothing" 0 \
  "$(rows '/api/blogs?filters[currentStatus]=draft&pagination[pageSize]=100')"
check "a student asking for drafts gets nothing" 0 \
  "$(rows '/api/blogs?filters[currentStatus]=draft&pagination[pageSize]=100' "$T_S1")"
# 404 rather than 403: the existence of an unpublished post is not public either.
check "anonymous findOne on a draft -> 404" 404 "$(status GET "/api/blogs/$DRAFT_BLOG")"
check "a student findOne on a draft -> 404" 404 "$(status GET "/api/blogs/$DRAFT_BLOG" "$T_S1")"
check "anonymous findOne on a published post -> 200" 200 \
  "$(status GET "/api/blogs/$PUBLISHED_BLOG")"
check "the author can read their own draft" 200 "$(status GET "/api/blogs/$DRAFT_BLOG" "$T_CM")"
check "a student cannot publish a post" 403 \
  "$(status PUT "/api/blogs/$DRAFT_BLOG/publish" "$T_S1" '{}')"

echo
echo "=== reporting endpoints ==="
check "the course's instructor sees the roster" 200 \
  "$(status GET "/api/courses/$COURSE/students-progress" "$T_I1")"
check "another instructor does not" 403 \
  "$(status GET "/api/courses/$COURSE/students-progress" "$T_I2")"
check "a student does not" 403 \
  "$(status GET "/api/courses/$COURSE/students-progress" "$T_S1")"
check "an admin reads platform stats" 200 "$(status GET '/api/admin/stats' "$T_ADMIN")"
check "an instructor does not" 403 "$(status GET '/api/admin/stats' "$T_I1")"
check "a student does not" 403 "$(status GET '/api/admin/stats' "$T_S1")"
# Content managers author content; they do not report on accounts.
check "nor a content manager" 403 "$(status GET '/api/admin/stats' "$T_CM")"
check "nor an anonymous caller" 403 "$(status GET '/api/admin/stats')"

echo
echo "=== the admin assigns roles from the app, not the Strapi panel ==="
check "an admin reads the account directory" 200 "$(status GET '/api/admin/users' "$T_ADMIN")"
check "a content manager does not" 403 "$(status GET '/api/admin/users' "$T_CM")"
check "an instructor does not" 403 "$(status GET '/api/admin/users' "$T_I1")"
check "a student does not" 403 "$(status GET '/api/admin/users' "$T_S1")"
check "nor an anonymous caller" 403 "$(status GET '/api/admin/users')"

DIRECTORY=$(get '/api/admin/users' "$T_ADMIN")
# `strapi.db.query` bypasses the REST sanitizers, so the controller names its
# columns explicitly. This is the assertion that catches a `select` widened by
# accident: the user type carries all three of these.
check "no credential fields ride along" 0 \
  "$(printf '%s' "$DIRECTORY" | grep -oE '"(password|resetPasswordToken|confirmationToken)"' | wc -l)"
check "the four assignable roles come with it" 4 \
  "$(printf '%s' "$DIRECTORY" |
     grep -oP '"type":"\K(authenticated|instructor|content_manager|admin)' | sort -u | wc -l)"
# `public` is a real row in up_roles, and a user moved into it can no longer log in
# as anyone — so the endpoint never offers it and `setUserRole` refuses it below.
check "and the public role is not one of them" 0 \
  "$(printf '%s' "$DIRECTORY" | grep -o '"type":"public"' | wc -l)"

ADMINS_ONLY=$(get '/api/admin/users?role=admin' "$T_ADMIN")
check "the role filter keeps the admins" 1 \
  "$(printf '%s' "$ADMINS_ONLY" | grep -o '"email":"admin@demo.test"' | wc -l)"
check "and drops everyone else" 0 \
  "$(printf '%s' "$ADMINS_ONLY" | grep -o '"email":"student@demo.test"' | wc -l)"
check "search narrows the directory to one account" 1 \
  "$(get '/api/admin/users?q=instructor2@demo.test' "$T_ADMIN" | grep -o '"email":"[^"]*"' | wc -l)"

# instructor2 is the account this round trip moves, and it ends where it started
# because the ownership checks further down need it to be an instructor. Demoted
# first and promoted back, never the other way about: a failed restore then shows up
# as a FAIL right here, instead of quietly handing a content manager's reach to the
# token that is supposed to be refused two hundred lines later.
DEMOTED=$(put "/api/admin/users/$I2_USER_ID/role" "$T_ADMIN" '{"role":"authenticated"}')
check "an admin can change someone's role" authenticated \
  "$(printf '%s' "$DEMOTED" | grep -oP '"type":"\K[^"]+')"
# Re-read, because the response could be an echo of the payload rather than what
# the join table now says.
check "and the change is stored, not echoed" authenticated "$(role_of instructor2@demo.test)"
PROMOTED=$(put "/api/admin/users/$I2_USER_ID/role" "$T_ADMIN" '{"role":"instructor"}')
check "and promote them again" instructor \
  "$(printf '%s' "$PROMOTED" | grep -oP '"type":"\K[^"]+')"
check "back to the role the checks below need" instructor "$(role_of instructor2@demo.test)"

check "an unknown role type is refused" 400 \
  "$(status PUT "/api/admin/users/$I2_USER_ID/role" "$T_ADMIN" '{"role":"superuser"}')"
check "so is public, which exists but is not assignable" 400 \
  "$(status PUT "/api/admin/users/$I2_USER_ID/role" "$T_ADMIN" '{"role":"public"}')"
check "and a body naming no role at all" 400 \
  "$(status PUT "/api/admin/users/$I2_USER_ID/role" "$T_ADMIN" '{}')"
check "an id that is not a number is refused" 400 \
  "$(status PUT '/api/admin/users/nobody/role' "$T_ADMIN" '{"role":"instructor"}')"
check "and one that names nobody -> 404" 404 \
  "$(status PUT '/api/admin/users/99999999/role' "$T_ADMIN" '{"role":"instructor"}')"
# The check that stops the platform locking itself out. Role assignment lives behind
# this endpoint and nowhere else in the app, so an admin who demotes themselves — the
# only admin especially — has no way back in short of the Strapi panel.
check "an admin cannot change their own role" 400 \
  "$(status PUT "/api/admin/users/$ADMIN_USER_ID/role" "$T_ADMIN" '{"role":"authenticated"}')"
check "a content manager cannot assign roles" 403 \
  "$(status PUT "/api/admin/users/$I2_USER_ID/role" "$T_CM" '{"role":"admin"}')"
check "nor an instructor" 403 \
  "$(status PUT "/api/admin/users/$I2_USER_ID/role" "$T_I1" '{"role":"admin"}')"
check "nor a student promoting themselves" 403 \
  "$(status PUT "/api/admin/users/$S1_USER_ID/role" "$T_S1" '{"role":"admin"}')"
check "nor an anonymous caller" 403 \
  "$(status PUT "/api/admin/users/$S1_USER_ID/role" '' '{"role":"admin"}')"
# Refusing with the right status is not the same as refusing to write. Every attempt
# above named a real account with a real role; this is what proves none of them
# landed anyway.
check "and none of those refusals moved anyone" authenticated \
  "$(role_of student@demo.test)"
check "instructor2 included" instructor "$(role_of instructor2@demo.test)"
check "the admin least of all" admin "$(role_of admin@demo.test)"

echo
echo "=== what the frontend reads to render itself ==="
# The UI branches on role, and neither the login response nor /users/me will give
# it one: the login lookup runs no populate, and ?populate=role needs `find` on
# the role type — a grant that would also expose every role's permission set.
check "the caller's role reaches the client" authenticated \
  "$(get '/api/profile/me' "$T_S1" | grep -oP '"type":"\K[^"]+')"
check "and it is the caller's own role" instructor \
  "$(get '/api/profile/me' "$T_I1" | grep -oP '"type":"\K[^"]+')"
check "no password hash rides along" 0 \
  "$(get '/api/profile/me' "$T_ADMIN" | grep -o 'password' | wc -l)"
check "anonymous gets nothing" 403 "$(status GET '/api/profile/me')"

# `?mine=true` exists because the client-side equivalent is impossible: filtering
# by `creator` reaches into the user type, which the query validator rejects for
# any role without `user.find`.
#
# Scoped to the seeded slug rather than counting the catalog, because the catalog is
# not this suite's to predict — `npm run seed:courses` adds three more, and a real
# instance will have whatever its instructors have written. instructor2's list stays
# an unfiltered 0: it owns nothing anywhere, which is the stronger half of the claim.
check "an instructor's own courses include the one they created" 1 \
  "$(rows "/api/courses?mine=true&filters[slug]=$COURSE_SLUG&pagination[pageSize]=100" "$T_I1")"
check "another instructor's list is empty" 0 \
  "$(rows '/api/courses?mine=true&pagination[pageSize]=100' "$T_I2")"
check "while the catalog itself still carries it for them" 1 \
  "$(rows "/api/courses?filters[slug]=$COURSE_SLUG&pagination[pageSize]=100" "$T_I2")"
check "mine=true is not for anonymous callers" 401 "$(status GET '/api/courses?mine=true')"
# The client cannot reach a student's own rows through the user relation either,
# so these are the populates the frontend actually issues.
check "a student may populate a lesson through progress" 200 \
  "$(status GET '/api/lesson-progresses?populate[lesson][populate][0]=course' "$T_S1")"
check "and a quiz through a result" 200 \
  "$(status GET '/api/quiz-results?populate=quiz' "$T_S1")"
check "but not the user relation" 400 \
  "$(status GET '/api/quiz-results?filters[user][id]=2' "$T_S1")"
# Populating `user` is not an error — the sanitizer silently drops the relation
# rather than rejecting the request, so what matters is that no account detail
# rides along with the row.
check "and populating it yields no account data" 0 \
  "$(get '/api/quiz-results?populate=user' "$T_S1" | grep -oE '"(email|username)"' | wc -l)"

echo
echo "=== a post written from the frontend gets a usable URL ==="
# uid fields are filled by the admin panel's content-manager plugin, not by the
# content API, so a post created over REST arrives with `slug: null` — and the blog
# is addressed by slug, which would leave it unreachable at its own URL. The
# controller derives one on create.
SMOKE_SLUG=frontend-smoke-test-post
SMOKE_POST="{\"data\":{\"title\":\"Frontend Smoke Test Post\",\"body\":[{\"type\":\"paragraph\",\"children\":[{\"type\":\"text\",\"text\":\"Written by verify.sh.\"}]}]}}"

# Leftovers from an interrupted run would shift the collision suffix asserted
# below, so they go first.
for leftover in $(ids "/api/blogs?filters[slug][\$startsWith]=$SMOKE_SLUG&pagination[pageSize]=100" "$T_ADMIN"); do
  status DELETE "/api/blogs/$leftover" "$T_ADMIN" > /dev/null
done

SMOKE_1=$(post '/api/blogs' "$T_CM" "$SMOKE_POST")
check "a slug is derived from the title" "$SMOKE_SLUG" \
  "$(printf '%s' "$SMOKE_1" | grep -oP '"slug":"\K[^"]+' | head -1)"
check "and the post starts as a draft" draft \
  "$(printf '%s' "$SMOKE_1" | grep -oP '"currentStatus":"\K[^"]+' | head -1)"

# `slug` is a uid, so it carries a unique index: a second post with the same title
# must not be rejected by it.
SMOKE_2=$(post '/api/blogs' "$T_CM" "$SMOKE_POST")
check "a repeated title does not collide" "$SMOKE_SLUG-2" \
  "$(printf '%s' "$SMOKE_2" | grep -oP '"slug":"\K[^"]+' | head -1)"

# Removed again so the post counts asserted earlier still hold on the next run.
for created in $(printf '%s%s' "$SMOKE_1" "$SMOKE_2" | grep -oP '"documentId":"\K[^"]+'); do
  check "the smoke post is cleaned up" 204 "$(status DELETE "/api/blogs/$created" "$T_CM")"
done
check "leaving the published count as it was" 1 \
  "$(rows '/api/blogs?pagination[pageSize]=100' "$T_S1")"

echo
echo "=== creating a course and enrolling attach an owner ==="
# `Course.creator`, `Blog.author` and `Enrollment.user` all point at the
# users-permissions user, and the content API rejects any *payload key* reaching a
# type the caller cannot `find` — which is every role here — so all three creates
# were returning `400 Invalid key <field>`. Ownership is stamped through the
# Document Service after the row exists, so these assert the attribution and not
# merely a 2xx: a course with no creator is one its own author cannot edit.
# How big the catalog is before this section adds to it. The cleanup at the end
# asserts the same number again — an absolute count would only ever be right on a
# pristine seed, and what actually matters is that nothing this suite created
# outlives it.
CATALOG_BEFORE=$(rows '/api/courses?pagination[pageSize]=100' "$T_S1")

SMOKE_COURSE=$(post '/api/courses' "$T_I2" \
  '{"data":{"title":"Ownership Smoke Course","description":"Created by verify.sh."}}')
SMOKE_COURSE_ID=$(printf '%s' "$SMOKE_COURSE" | grep -oP '"documentId":"\K[^"]+' | head -1)

check "an instructor can create a course" ok "${SMOKE_COURSE_ID:+ok}"
check "and a slug is derived for it" ownership-smoke-course \
  "$(printf '%s' "$SMOKE_COURSE" | grep -oP '"slug":"\K[^"]+' | head -1)"
check "it is attributed to its creator" 1 \
  "$(rows "/api/courses?mine=true&filters[documentId]=$SMOKE_COURSE_ID" "$T_I2")"
check "not to another instructor" 0 \
  "$(rows "/api/courses?mine=true&filters[documentId]=$SMOKE_COURSE_ID" "$T_I1")"
# The attribution has to hold for the ownership policies too, which read the
# course rather than the caller's own list.
check "and its creator may edit it" 200 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID" "$T_I2" '{"data":{"description":"Edited."}}')"

# A lesson with a quiz on it, so the approval and gate assertions below have
# something real to work on. This is also the authoring path the frontend editor
# drives: create the lesson, then attach a quiz to it.
#
# `correctOptionIndex` is `private`, so it is stripped from every response — but it
# is writable, and the only way to observe that it landed is to have the server
# grade an answer against it, which is what the gate section does.
SMOKE_LESSON=$(post '/api/lessons' "$T_I2" \
  "{\"data\":{\"title\":\"Gated Lesson\",\"sequenceOrder\":1,\"course\":\"$SMOKE_COURSE_ID\"}}")
SMOKE_LESSON_ID=$(printf '%s' "$SMOKE_LESSON" | grep -oP '"documentId":"\K[^"]+' | head -1)
SMOKE_QUIZ=$(post '/api/quizzes' "$T_I2" \
  "{\"data\":{\"lesson\":\"$SMOKE_LESSON_ID\",\"Question\":[{\"questionText\":\"2+2?\",\"options\":[\"3\",\"4\",\"5\"],\"correctOptionIndex\":1}]}}")
SMOKE_QUIZ_ID=$(printf '%s' "$SMOKE_QUIZ" | grep -oP '"documentId":"\K[^"]+' | head -1)

check "an instructor can add a lesson to their own course" ok "${SMOKE_LESSON_ID:+ok}"
check "and attach a quiz to that lesson" ok "${SMOKE_QUIZ_ID:+ok}"
# The seeded quiz is checked earlier; this is the same guarantee for one written
# over REST, where the key was supplied by the client rather than by the seed.
check "the answer key does not come back out" 0 \
  "$(get "/api/quizzes/$SMOKE_QUIZ_ID?populate=Question" "$T_I2" | grep -c correctOptionIndex || true)"

# student2 has no enrollment anywhere, so its list is a clean before/after.
S2_BEFORE=$(rows '/api/enrollments?pagination[pageSize]=100' "$T_S2")
check "a student can request enrolment" 201 \
  "$(status POST '/api/enrollments' "$T_S2" "{\"data\":{\"course\":\"$SMOKE_COURSE_ID\"}}")"
check "the request belongs to them" "$((S2_BEFORE + 1))" \
  "$(rows '/api/enrollments?pagination[pageSize]=100' "$T_S2")"
# Without a `user` the row would belong to nobody, and the `find` scope on
# enrollments is by user — so an unowned row is invisible to its own student. That
# the *other* student's list does not contain it is what proves the relation landed
# on the account that asked for it rather than on whoever happened to be first.
check "and not to another student" 0 \
  "$(rows "/api/enrollments?filters[course][documentId]=$SMOKE_COURSE_ID&pagination[pageSize]=100" "$T_S1")"
# A pending request is still a row, so asking twice conflicts rather than queueing a
# second one.
check "requesting again is a conflict" 409 \
  "$(status POST '/api/enrollments' "$T_S2" "{\"data\":{\"course\":\"$SMOKE_COURSE_ID\"}}")"

# The enrollment's own documentId, read from the student's scoped list rather than
# from the create response, so what is asserted below is the *stored* status and not
# an echo of the payload.
SMOKE_ENROL_ID=$(ids \
  "/api/enrollments?filters[course][documentId]=$SMOKE_COURSE_ID&pagination[pageSize]=100" "$T_S2")

echo
echo "=== a request is not an enrolment until staff approve it ==="
check "a new request starts as pending" pending \
  "$(get "/api/enrollments/$SMOKE_ENROL_ID" "$T_S2" | grep -oP '"current_status":"\K[^"]+')"
check "a pending student cannot complete a lesson" 403 \
  "$(status POST "/api/lessons/$SMOKE_LESSON_ID/complete" "$T_S2" '{}')"
check "a pending student cannot submit its quiz" 403 \
  "$(status POST "/api/quizzes/$SMOKE_QUIZ_ID/submit" "$T_S2" '{"answers":[1]}')"
# Refusing the submission is not enough on its own: a pending student who could
# still read the paper would have the questions in hand before the approval that
# lets them answer, which is most of the point of having a quiz.
check "nor even read its questions" 0 \
  "$(get "/api/quizzes/$SMOKE_QUIZ_ID?populate=Question" "$T_S2" | grep -o '"questionText"' | wc -l)"
check "nor reach them through the course" 0 \
  "$(get "/api/courses/$SMOKE_COURSE_ID?populate[lessons][populate][quiz][populate][0]=Question" \
    "$T_S2" | grep -o '"questionText"' | wc -l)"
# The sharpest version of the same vector, and the one that would make the whole
# approval step pointless: anyone may request enrolment in any course, and the
# request is a row they own — so a pending enrolment must not become a way to read
# the course through its own `course` relation.
check "nor through the pending request itself" 0 \
  "$(get "/api/enrollments?populate[course][populate][lessons][populate][quiz][populate][0]=Question" \
    "$T_S2" | grep -o '"questionText"' | wc -l)"
# The shape is not withheld, and this is the row the course page renders for a
# student still waiting: the lesson is there, titled, with its quiz flagged.
check "but the lesson itself is still listed" 1 \
  "$(get "/api/courses/$SMOKE_COURSE_ID?populate[lessons]=true" "$T_S2" \
    | grep -o '"sequenceOrder"' | wc -l)"
# The bypass, and the assertion that matters most in this section: `/complete` is
# not the only way to write a completed row, so gating it alone would leave the
# whole approval step one POST away from irrelevant.
check "nor write the progress row directly" 403 \
  "$(status POST '/api/lesson-progresses' "$T_S2" \
    "{\"data\":{\"lesson\":\"$SMOKE_LESSON_ID\",\"completed\":true}}")"
check "the student cannot approve their own request" 403 \
  "$(status POST "/api/enrollments/$SMOKE_ENROL_ID/approve" "$T_S2" '{}')"
check "an instructor of another course cannot approve it" 403 \
  "$(status POST "/api/enrollments/$SMOKE_ENROL_ID/approve" "$T_I1" '{}')"
check "the course's own instructor can" 200 \
  "$(status POST "/api/enrollments/$SMOKE_ENROL_ID/approve" "$T_I2" '{}')"
check "and the stored status says so" approved \
  "$(get "/api/enrollments/$SMOKE_ENROL_ID" "$T_S2" | grep -oP '"current_status":"\K[^"]+')"
# The same three requests as above, same account, same course — the only thing that
# changed is the instructor's decision. This is the one place the rule is proven end
# to end, and it is also the guard against over-redaction: a gate that never opens
# would pass every check in the section above.
check "and now the questions are readable" 1 \
  "$(get "/api/quizzes/$SMOKE_QUIZ_ID?populate=Question" "$T_S2" | grep -o '"questionText"' | wc -l)"
check "through the course as well" 1 \
  "$(get "/api/courses/$SMOKE_COURSE_ID?populate[lessons][populate][quiz][populate][0]=Question" \
    "$T_S2" | grep -o '"questionText"' | wc -l)"
check "and through the enrolment that granted it" 1 \
  "$(get "/api/enrollments?populate[course][populate][lessons][populate][quiz][populate][0]=Question" \
    "$T_S2" | grep -o '"questionText"' | wc -l)"

echo
echo "=== a lesson with a quiz is not done until the quiz is passed ==="
# Approved, so enrolment is no longer what stands in the way — the quiz is.
check "an approved student still cannot complete a gated lesson" 403 \
  "$(status POST "/api/lessons/$SMOKE_LESSON_ID/complete" "$T_S2" '{}')"
check "nor write the progress row directly" 403 \
  "$(status POST '/api/lesson-progresses' "$T_S2" \
    "{\"data\":{\"lesson\":\"$SMOKE_LESSON_ID\",\"completed\":true}}")"

WRONG=$(post "/api/quizzes/$SMOKE_QUIZ_ID/submit" "$T_S2" '{"answers":[0]}')
check "a wrong answer is graded against the hidden key" false \
  "$(printf '%s' "$WRONG" | grep -oP '"passed":\K(true|false)')"
check "a lesson quiz records a result" true \
  "$(printf '%s' "$WRONG" | grep -oP '"recorded":\K(true|false)')"
# The number the frontend renders comes from here, not from a copy in the client.
check "the pass mark is reported by the server" 60 \
  "$(printf '%s' "$WRONG" | grep -oP '"passMark":\K[0-9]+')"
check "and a failing score still blocks completion" 403 \
  "$(status POST "/api/lessons/$SMOKE_LESSON_ID/complete" "$T_S2" '{}')"

RIGHT=$(post "/api/quizzes/$SMOKE_QUIZ_ID/submit" "$T_S2" '{"answers":[1]}')
check "the correct answer passes" true \
  "$(printf '%s' "$RIGHT" | grep -oP '"passed":\K(true|false)')"
check "which unlocks the lesson" 200 \
  "$(status POST "/api/lessons/$SMOKE_LESSON_ID/complete" "$T_S2" '{}')"
# Un-completing writes through the same endpoint as the forged completion above, so
# the gate keys on the direction rather than the endpoint. If it did not, the UI's
# own toggle would be the first thing it broke.
check "and un-completing is never gated" 201 \
  "$(status POST '/api/lesson-progresses' "$T_S2" \
    "{\"data\":{\"lesson\":\"$SMOKE_LESSON_ID\",\"completed\":false}}")"
# Two submissions, one row: the result is upserted on (user, quiz), so a retake
# replaces the score rather than appending an attempt.
check "two attempts leave one result row" 1 \
  "$(rows '/api/quiz-results?pagination[pageSize]=100' "$T_S2")"

echo
echo "=== rewriting a quiz rewrites what the grader marks against ==="
# The whole point of the in-app editor: an author loads a quiz through `manage`,
# changes the questions and the key, and saves through the ordinary PUT — because
# `private` is output-only in Strapi 5, so `correctOptionIndex` was always writable
# and only ever unreadable.
#
# Asserted end to end rather than by reading the row back, because a key that is
# stored but not the one `submit` consults would pass every read-side check here.
check "the lesson's own instructor can replace the questions" 200 \
  "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_I2" \
    '{"data":{"Question":[{"questionText":"Capital of France?","options":["Berlin","Paris","Rome"],"correctOptionIndex":1},{"questionText":"2+2?","options":["3","4"],"correctOptionIndex":1}]}}')"
check "and reads the new key back through manage" 11 \
  "$(get "/api/quizzes/$SMOKE_QUIZ_ID/manage" "$T_I2" | grep -oP '"correctOptionIndex":\K[0-9]+' | tr -d '\n')"
# A key written over REST is stripped on the way out exactly like a seeded one. The
# student here is enrolled and approved, so this is the strongest form of the claim:
# they may read the paper and still not the answers.
check "while the student taking it still cannot" 0 \
  "$(get "/api/quizzes/$SMOKE_QUIZ_ID?populate=Question" "$T_S2" | grep -c correctOptionIndex || true)"
check "but does get both questions" 2 \
  "$(get "/api/quizzes/$SMOKE_QUIZ_ID?populate=Question" "$T_S2" | grep -o '"questionText"' | wc -l)"
check "the grader marks against the key just written" 100 \
  "$(post "/api/quizzes/$SMOKE_QUIZ_ID/submit" "$T_S2" '{"answers":[1,1]}' | num score)"
# The answers that used to be right — one question, key 1 — now score half, which is
# what proves the old key is gone rather than merely overwritten in the response.
check "and the previous key no longer passes" 50 \
  "$(post "/api/quizzes/$SMOKE_QUIZ_ID/submit" "$T_S2" '{"answers":[0,1]}' | num score)"
check "an instructor who does not own the lesson cannot rewrite it" 403 \
  "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_I1" \
    '{"data":{"Question":[{"questionText":"Whose quiz?","options":["mine","yours"],"correctOptionIndex":0}]}}')"
check "and a student cannot rewrite it at all" 403 \
  "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_S2" \
    '{"data":{"Question":[{"questionText":"2+2?","options":["3","4"],"correctOptionIndex":0}]}}')"
check "so the key survived both attempts" 11 \
  "$(get "/api/quizzes/$SMOKE_QUIZ_ID/manage" "$T_I2" | grep -oP '"correctOptionIndex":\K[0-9]+' | tr -d '\n')"

echo
echo "=== a declined request is final until staff reopen it ==="
check "the course's instructor can decline" 200 \
  "$(status POST "/api/enrollments/$SMOKE_ENROL_ID/reject" "$T_I2" '{}')"
check "a declined student loses access again" 403 \
  "$(status POST "/api/lessons/$SMOKE_LESSON_ID/complete" "$T_S2" '{}')"
check "their own retry is a conflict, not a fresh request" 409 \
  "$(status POST '/api/enrollments' "$T_S2" "{\"data\":{\"course\":\"$SMOKE_COURSE_ID\"}}")"
check "and no second row appeared" 1 \
  "$(rows '/api/enrollments?pagination[pageSize]=100' "$T_S2")"
check "a student cannot reopen it themselves" 403 \
  "$(status POST "/api/enrollments/$SMOKE_ENROL_ID/reopen" "$T_S2" '{}')"
check "staff can" 200 \
  "$(status POST "/api/enrollments/$SMOKE_ENROL_ID/reopen" "$T_I2" '{}')"
check "which returns it to pending" pending \
  "$(get "/api/enrollments/$SMOKE_ENROL_ID" "$T_S2" | grep -oP '"current_status":"\K[^"]+')"

echo
echo "=== a quiz only a lesson reaches still has an owner ==="
# A quiz reaches its course through `course`, `parent_course`, or the lesson it
# gates. Before the third was resolved, a lesson-only quiz — the normal case for a
# gated lesson — had no course, so `can-manage-quiz` denied every write on it,
# including an admin's. And an instructor could pair their own `parent_course` with
# someone else's `lesson` in one create and gate a lesson they do not own.
check "another instructor cannot gate this lesson with their quiz" 403 \
  "$(status POST '/api/quizzes' "$T_I1" \
    "{\"data\":{\"parent_course\":\"$COURSE\",\"lesson\":\"$SMOKE_LESSON_ID\"}}")"
check "another instructor cannot empty its questions" 403 \
  "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_I1" '{"data":{"Question":[]}}')"
check "the lesson's own instructor can write to it" 200 \
  "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_I2" '{"data":{}}')"
check "and so can an admin" 200 \
  "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_ADMIN" '{"data":{}}')"

echo
echo "=== a malformed question set is refused before it is stored ==="
# `options` is a json column and `correctOptionIndex` a plain integer, so the schema
# validates neither the shape of one nor the range of the other. A quiz whose key
# points past its own options is one nobody can pass, with no error anywhere: the
# grader compares an answer against an index that does not exist, marks it wrong, and
# the student is told they failed. So the controller checks the shape on the way in.
for probe in \
  'no question text:{"questionText":"   ","options":["3","4"],"correctOptionIndex":0}' \
  'a single option:{"questionText":"2+2?","options":["4"],"correctOptionIndex":0}' \
  'a blank option:{"questionText":"2+2?","options":["4",""],"correctOptionIndex":0}' \
  'an option that is not text:{"questionText":"2+2?","options":["4",7],"correctOptionIndex":0}' \
  'options that are not a list:{"questionText":"2+2?","options":"3,4","correctOptionIndex":0}' \
  'a key past the last option:{"questionText":"2+2?","options":["3","4"],"correctOptionIndex":2}' \
  'a negative key:{"questionText":"2+2?","options":["3","4"],"correctOptionIndex":-1}' \
  'a fractional key:{"questionText":"2+2?","options":["3","4"],"correctOptionIndex":0.5}' \
  'no key at all:{"questionText":"2+2?","options":["3","4"]}' \
  ; do
  label=${probe%%:*}
  body=${probe#*:}
  check "creating a quiz with $label" 400 \
    "$(status POST '/api/quizzes' "$T_I2" \
      "{\"data\":{\"parent_course\":\"$SMOKE_COURSE_ID\",\"Question\":[$body]}}")"
  check "and rewriting one with it" 400 \
    "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_I2" "{\"data\":{\"Question\":[$body]}}")"
done

# A 400 is only half the claim; the other half is that nothing was written anyway.
check "so nothing was created by any of them" 0 \
  "$(rows "/api/quizzes?filters[parent_course][documentId]=$SMOKE_COURSE_ID" "$T_ADMIN")"
check "and the question set already there survived" 11 \
  "$(get "/api/quizzes/$SMOKE_QUIZ_ID/manage" "$T_I2" | grep -oP '"correctOptionIndex":\K[0-9]+' | tr -d '\n')"
# The validator only fires when the payload carries `Question`. The course editor
# attaches and detaches quizzes with relation-only writes, and refusing those for
# "having no questions" would break the attach dropdown.
check "but a relation-only write is not judged on its questions" 200 \
  "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_I2" "{\"data\":{\"lesson\":\"$SMOKE_LESSON_ID\"}}")"
# Emptying a quiz is a legitimate edit, so an empty list is accepted where a
# malformed one is not. The editor asks for at least one question; the API does not.
check "and an empty question set is accepted" 200 \
  "$(status PUT "/api/quizzes/$SMOKE_QUIZ_ID" "$T_I2" '{"data":{"Question":[]}}')"

echo
echo "=== promoting a quiz to the final moves it rather than copying it ==="
# `Course.final_quiz` is the owning side of that relation, so the link can only be
# written from the course — setting `quiz.course` from the quiz side silently does
# nothing at all. PUT /courses/:id/final-quiz exists so the frontend never has to
# know that, and it is also where the demotion below happens.
#
# A quiz has no type column: which relation is set is what makes it final, practice
# or a lesson gate, so the kind is read back through `manage` rather than inferred.
# Every match is reported, not the first one, because a quiz left on two relations at
# once is exactly the bug being checked for.
kind_of() {
  get "/api/quizzes/$1/manage" "$T_ADMIN" |
    grep -oP '"is(Final|Lesson|Practice)":true' | tr -d '"' | tr '\n' ' ' | sed 's/ *$//'
}

# The course exactly as `getCourse` in the frontend asks for it — a plain read, so
# the *published* version, which is the whole point: the authoring endpoint has to
# write where readers look.
course_view() {
  get "/api/courses/$SMOKE_COURSE_ID?populate[final_quiz]=true&populate[practice_quizzes]=true&fields[0]=title" \
    "$T_I2"
}

# The final quiz's documentId out of that, or empty when the slot is clear. Scoped to
# the `final_quiz` object rather than taking the first documentId in the body, which
# is the course's own. Safe as a flat match because a populated relation with no
# populate of its own carries no nested object.
final_quiz_of() {
  printf '%s' "$1" | grep -oP '"final_quiz":\{[^}]*\}' | grep -oP '"documentId":"\K[^"]+'
}

new_practice() {
  post '/api/quizzes' "$T_I2" \
    "{\"data\":{\"parent_course\":\"$SMOKE_COURSE_ID\",\"Question\":[{\"questionText\":\"$1\",\"options\":[\"a\",\"b\"],\"correctOptionIndex\":0}]}}" |
    grep -oP '"documentId":"\K[^"]+' | head -1
}

SMOKE_P1=$(new_practice 'Practice one?')
SMOKE_P2=$(new_practice 'Practice two?')
check "an instructor can add a practice quiz to their course" ok "${SMOKE_P1:+ok}"
check "and a second one" ok "${SMOKE_P2:+ok}"
check "a practice quiz starts as practice" isPractice:true "$(kind_of "$SMOKE_P1")"

check "another instructor cannot set this course's final quiz" 403 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_I1" "{\"quiz\":\"$SMOKE_P1\"}")"
check "nor a student enrolled in it" 403 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_S2" "{\"quiz\":\"$SMOKE_P1\"}")"
check "nor an anonymous caller" 403 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID/final-quiz" '' "{\"quiz\":\"$SMOKE_P1\"}")"
check "and the quiz is untouched by those attempts" isPractice:true "$(kind_of "$SMOKE_P1")"

PROMOTED_QUIZ=$(put "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_I2" "{\"quiz\":\"$SMOKE_P1\"}")
check "the course's own instructor can" "$SMOKE_P1" \
  "$(printf '%s' "$PROMOTED_QUIZ" | grep -oP '"finalQuizId":"\K[^"]+')"
# The failure this rules out is `isFinal:true isPractice:true`: a quiz left on both
# relations is offered twice on the course page and graded under whichever one
# resolves first.
check "and it is the final quiz only" isFinal:true "$(kind_of "$SMOKE_P1")"
# Read back through the *published* version, which is what every reader of a course
# takes — `getCourse` in the frontend, the catalog, the course page. A handler that
# wrote only the draft would pass `kind_of` above and still set a final quiz that
# nothing outside the authoring screen could see.
check "the published course reports it as its final" "$SMOKE_P1" \
  "$(final_quiz_of "$(course_view)")"
check "and stops listing it as a practice quiz" 0 \
  "$(rows "/api/quizzes?filters[parent_course][documentId]=$SMOKE_COURSE_ID&filters[documentId]=$SMOKE_P1" "$T_I2")"

REPLACED=$(put "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_ADMIN" "{\"quiz\":\"$SMOKE_P2\"}")
check "an admin can replace it" "$SMOKE_P2" \
  "$(printf '%s' "$REPLACED" | grep -oP '"finalQuizId":"\K[^"]+')"
check "and the response names the quiz it displaced" "$SMOKE_P1" \
  "$(printf '%s' "$REPLACED" | grep -oP '"demotedToPractice":"\K[^"]+')"
check "the published course reports the replacement" "$SMOKE_P2" \
  "$(final_quiz_of "$(course_view)")"
# The displaced quiz has to land somewhere. With none of the three relations set it
# resolves to no course at all, which makes it uneditable and undeletable over REST
# and ungradeable — an orphan nobody can reach even to clean up.
check "so it is a practice quiz again, not an orphan" isPractice:true "$(kind_of "$SMOKE_P1")"
check "and the course lists it as one" 1 \
  "$(rows "/api/quizzes?filters[parent_course][documentId]=$SMOKE_COURSE_ID&filters[documentId]=$SMOKE_P1" "$T_I2")"

CLEARED=$(put "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_I2" '{"quiz":null}')
check "the final quiz can be unset" '"finalQuizId":null' \
  "$(printf '%s' "$CLEARED" | grep -o '"finalQuizId":null')"
check "and unsetting demotes rather than orphans" isPractice:true "$(kind_of "$SMOKE_P2")"
check "the course lists that one as practice too" 1 \
  "$(rows "/api/quizzes?filters[parent_course][documentId]=$SMOKE_COURSE_ID&filters[documentId]=$SMOKE_P2" "$T_I2")"
check "leaving the published course with no final quiz" '' "$(final_quiz_of "$(course_view)")"

# A quiz belongs in one place. Stealing one off the lesson it gates would break that
# gate silently, and taking one from another course would break that course.
check "a quiz that gates a lesson cannot also be the final" 400 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_I2" "{\"quiz\":\"$SMOKE_QUIZ_ID\"}")"
check "nor can one belonging to another course" 400 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_I2" "{\"quiz\":\"$PRACTICE_QUIZ\"}")"
check "a quiz that does not exist -> 404" 404 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_I2" '{"quiz":"nosuchquiz"}')"
check "a body naming neither a quiz nor null -> 400" 400 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_I2" '{"quiz":7}')"
check "and an empty body -> 400" 400 \
  "$(status PUT "/api/courses/$SMOKE_COURSE_ID/final-quiz" "$T_I2" '{}')"
check "the seeded course kept its own lesson gate" isLesson:true "$(kind_of "$SMOKE_QUIZ_ID")"
check "and its practice quiz stayed a practice quiz" isPractice:true "$(kind_of "$PRACTICE_QUIZ")"

echo
# Cleaned up in dependency order — the rows that point at the course before the
# course itself, so nothing is left pointing at something that no longer exists.
# Each delete is its own assertion: a cleanup that silently fails would surface as
# an unrelated scoping failure on the *next* run, two hundred lines earlier.
check "one progress row was left behind to clean up" 1 \
  "$(rows '/api/lesson-progresses?pagination[pageSize]=100' "$T_S2")"
for created in $(ids '/api/quiz-results?pagination[pageSize]=100' "$T_S2"); do
  check "the smoke quiz result is cleaned up" 204 \
    "$(status DELETE "/api/quiz-results/$created" "$T_ADMIN")"
done
# Deleting the lesson does not take its progress rows with it — Strapi drops the
# relation link, not the related entry — so these go first and explicitly.
for created in $(ids '/api/lesson-progresses?pagination[pageSize]=100' "$T_S2"); do
  check "the smoke progress row is cleaned up" 204 \
    "$(status DELETE "/api/lesson-progresses/$created" "$T_ADMIN")"
done
for created in $(ids "/api/enrollments?filters[course][documentId]=$SMOKE_COURSE_ID&pagination[pageSize]=100" "$T_ADMIN"); do
  check "the smoke enrollment is cleaned up" 204 \
    "$(status DELETE "/api/enrollments/$created" "$T_ADMIN")"
done
check "the smoke quiz is cleaned up" 204 \
  "$(status DELETE "/api/quizzes/$SMOKE_QUIZ_ID" "$T_I2")"
# The two practice quizzes go before the course as well. Both are reachable only
# through `parent_course`, so deleting the course first would leave them resolving to
# nothing — the orphan state the promotion checks above exist to prevent, created by
# the cleanup instead.
check "the first practice quiz is cleaned up" 204 \
  "$(status DELETE "/api/quizzes/$SMOKE_P1" "$T_I2")"
check "the second practice quiz is cleaned up" 204 \
  "$(status DELETE "/api/quizzes/$SMOKE_P2" "$T_I2")"
check "the smoke lesson is cleaned up" 204 \
  "$(status DELETE "/api/lessons/$SMOKE_LESSON_ID" "$T_I2")"
check "the smoke course is cleaned up" 204 \
  "$(status DELETE "/api/courses/$SMOKE_COURSE_ID" "$T_I2")"
check "leaving the catalog as it was" "$CATALOG_BEFORE" \
  "$(rows '/api/courses?pagination[pageSize]=100' "$T_S1")"
check "and student2 owning nothing again" 0 \
  "$(rows '/api/lesson-progresses?pagination[pageSize]=100' "$T_S2")"

echo
printf 'pass=%s fail=%s\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
